# Generated by Django 5.0.7 on 2024-07-27 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('L', 'Lagartija'), ('A', 'Agua'), ('F', 'Fuego'), ('E', 'Electrico'), ('P', 'Planta'), ('T', 'Tierra')], max_length=30),
        ),
    ]
