# Generated by Django 5.0.7 on 2024-07-27 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_alter_pokemon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('F', 'Fuego'), ('L', 'Lagartija'), ('E', 'Electrico'), ('P', 'Planta'), ('A', 'Agua'), ('T', 'Tierra')], max_length=30),
        ),
    ]
