# Generated by Django 5.0.7 on 2024-07-27 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0008_alter_pokemon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('F', 'Fuego'), ('A', 'Agua'), ('E', 'Electrico'), ('L', 'Lagartija'), ('T', 'Tierra'), ('P', 'Planta')], max_length=30),
        ),
    ]
