# Generated by Django 5.0.7 on 2024-07-27 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0014_alter_pokemon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('A', 'Agua'), ('P', 'Planta'), ('F', 'Fuego'), ('T', 'Tierra'), ('L', 'Lagartija'), ('E', 'Electrico')], max_length=30),
        ),
    ]
